package com.xiaoke_1256.orders.bigdata.product.model;

import java.math.BigDecimal;
import java.util.Date;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_code
     *
     * @mbg.generated Wed Aug 28 16:03:57 CST 2024
     */
    private String productCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_name
     *
     * @mbg.generated Wed Aug 28 16:03:57 CST 2024
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_price
     *
     * @mbg.generated Wed Aug 28 16:03:57 CST 2024
     */
    private BigDecimal productPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.store_no
     *
     * @mbg.generated Wed Aug 28 16:03:57 CST 2024
     */
    private String storeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_status
     *
     * @mbg.generated Wed Aug 28 16:03:57 CST 2024
     */
    private String productStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.on_sale_time
     *
     * @mbg.generated Wed Aug 28 16:03:57 CST 2024
     */
    private Date onSaleTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_intro
     *
     * @mbg.generated Wed Aug 28 16:03:57 CST 2024
     */
    private String productIntro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.brand
     *
     * @mbg.generated Wed Aug 28 16:03:57 CST 2024
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.insert_time
     *
     * @mbg.generated Wed Aug 28 16:03:57 CST 2024
     */
    private Date insertTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.update_time
     *
     * @mbg.generated Wed Aug 28 16:03:57 CST 2024
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.IN_SECKILL
     *
     * @mbg.generated Wed Aug 28 16:03:57 CST 2024
     */
    private String inSeckill;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_code
     *
     * @return the value of product.product_code
     *
     * @mbg.generated Wed Aug 28 16:03:57 CST 2024
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_code
     *
     * @param productCode the value for product.product_code
     *
     * @mbg.generated Wed Aug 28 16:03:57 CST 2024
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_name
     *
     * @return the value of product.product_name
     *
     * @mbg.generated Wed Aug 28 16:03:57 CST 2024
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_name
     *
     * @param productName the value for product.product_name
     *
     * @mbg.generated Wed Aug 28 16:03:57 CST 2024
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_price
     *
     * @return the value of product.product_price
     *
     * @mbg.generated Wed Aug 28 16:03:57 CST 2024
     */
    public BigDecimal getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_price
     *
     * @param productPrice the value for product.product_price
     *
     * @mbg.generated Wed Aug 28 16:03:57 CST 2024
     */
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.store_no
     *
     * @return the value of product.store_no
     *
     * @mbg.generated Wed Aug 28 16:03:57 CST 2024
     */
    public String getStoreNo() {
        return storeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.store_no
     *
     * @param storeNo the value for product.store_no
     *
     * @mbg.generated Wed Aug 28 16:03:57 CST 2024
     */
    public void setStoreNo(String storeNo) {
        this.storeNo = storeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_status
     *
     * @return the value of product.product_status
     *
     * @mbg.generated Wed Aug 28 16:03:57 CST 2024
     */
    public String getProductStatus() {
        return productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_status
     *
     * @param productStatus the value for product.product_status
     *
     * @mbg.generated Wed Aug 28 16:03:57 CST 2024
     */
    public void setProductStatus(String productStatus) {
        this.productStatus = productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.on_sale_time
     *
     * @return the value of product.on_sale_time
     *
     * @mbg.generated Wed Aug 28 16:03:57 CST 2024
     */
    public Date getOnSaleTime() {
        return onSaleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.on_sale_time
     *
     * @param onSaleTime the value for product.on_sale_time
     *
     * @mbg.generated Wed Aug 28 16:03:57 CST 2024
     */
    public void setOnSaleTime(Date onSaleTime) {
        this.onSaleTime = onSaleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_intro
     *
     * @return the value of product.product_intro
     *
     * @mbg.generated Wed Aug 28 16:03:57 CST 2024
     */
    public String getProductIntro() {
        return productIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_intro
     *
     * @param productIntro the value for product.product_intro
     *
     * @mbg.generated Wed Aug 28 16:03:57 CST 2024
     */
    public void setProductIntro(String productIntro) {
        this.productIntro = productIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.brand
     *
     * @return the value of product.brand
     *
     * @mbg.generated Wed Aug 28 16:03:57 CST 2024
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.brand
     *
     * @param brand the value for product.brand
     *
     * @mbg.generated Wed Aug 28 16:03:57 CST 2024
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.insert_time
     *
     * @return the value of product.insert_time
     *
     * @mbg.generated Wed Aug 28 16:03:57 CST 2024
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.insert_time
     *
     * @param insertTime the value for product.insert_time
     *
     * @mbg.generated Wed Aug 28 16:03:57 CST 2024
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.update_time
     *
     * @return the value of product.update_time
     *
     * @mbg.generated Wed Aug 28 16:03:57 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.update_time
     *
     * @param updateTime the value for product.update_time
     *
     * @mbg.generated Wed Aug 28 16:03:57 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.IN_SECKILL
     *
     * @return the value of product.IN_SECKILL
     *
     * @mbg.generated Wed Aug 28 16:03:57 CST 2024
     */
    public String getInSeckill() {
        return inSeckill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.IN_SECKILL
     *
     * @param inSeckill the value for product.IN_SECKILL
     *
     * @mbg.generated Wed Aug 28 16:03:57 CST 2024
     */
    public void setInSeckill(String inSeckill) {
        this.inSeckill = inSeckill;
    }
}