spring:
  profiles:
    active: dev
  application:
    name: orders-bigdata
  thymeleaf:
    cache: false
    enabled: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    drive-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.249.101:3306/big_data?characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true
    username: bigDataUser
    password: xiaoke_1256
    druid:
      validation-query: select 1
      min-idle: 10
      initial-size: 10
      max-active: 50
      time-between-eviction-runs-millis: 60000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false

server:
  context-path: /bigdata
  port: 8080
  servlet-path: /

mybatis:
  mapperLocations: classpath*:com/xiaoke_1256/orders/**/mapper/*Mapper.xml
  configLocation: classpath:sqlMapConfig.xml
#  configuration:
#    lazy-loading-enabled: true
#    aggressiveLazy-loading: false

logging:
  config: classpath:logback.xml

#spark 相关配置
spark:
  appName: orders-bigdata-algorithm
  master: spark://192.168.249.107:7077
  sql:
    shuffle:
      partitions: 1
  yarn:
    maxAppAttempts: 10
  blockManager:
    port: 10025
  driver:
    host: 192.168.40.1
    bindAddress: 0.0.0.0
    blockManager:
      port: 10026
  executor:
    memory: 512m
  #涉及到多个jar包则用逗号分割
  jars: D:\maven-repository\com\xiaoke_1256\orders\bigData-spark\1.0.0\bigData-spark-1.0.0.jar
  hdfs:
    uri: hdfs://master:8020

big-data:
  tmp-div: D:\tmp\orders\bigdata