apiVersion: v1
kind: ReplicationController
metadata:
  name: discovery-eureka-peer1
  labels:
    name: discovery-eureka-peer1
spec:
  replicas: 1
  selector:
    name: discovery-eureka-peer1
  template:
    metadata:
      labels:
        name: discovery-eureka-peer1
    spec:
      containers:
      - name: discovery-eureka
        image: repo.orders.com:5000/orders/discovery-eureka
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: peer1,prod
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://${DISCOVERY_EUREKA_PEER2_SERVICE_HOST}:${DISCOVERY_EUREKA_PEER2_SERVICE_PORT}/discovery/eureka/
        ports:
        - containerPort: 8761
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: discovery-eureka-peer2
  labels:
    name: discovery-eureka-peer2
spec:
  replicas: 1
  selector:
    name: discovery-eureka-peer2
  template:
    metadata:
      labels:
        name: discovery-eureka-peer2
    spec:
      containers:
      - name: discovery-eureka
        image: repo.orders.com:5000/orders/discovery-eureka
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: peer2,prod
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://${DISCOVERY_EUREKA_PEER1_SERVICE_HOST}:${DISCOVERY_EUREKA_PEER1_SERVICE_PORT}/discovery/eureka/
        ports:
        - containerPort: 8762