apiVersion: v1
kind: Service
metadata:
  name: discovery-eureka-peer1
  labels:
    name: discovery-eureka-peer1-service
spec:
  ports:
  - name: "8761"
    port: 8761
    targetPort: 8761
  selector:
    name: discovery-eureka-peer1
  type: LoadBalancer
  externalIPs:
  - 192.168.1.101  #需要根据环境调整
status:
  loadBalancer: {}