apiVersion: v1
kind: Service
metadata:
  name: discovery-eureka-peer1
  labels:
    name: discovery-eureka-peer1-service
spec:
  ports:
  - name: "8761"
    port: 8761
    targetPort: 8761
  selector:
    name: discovery-eureka-peer1
  type: LoadBalancer
  externalIPs:
  - 192.168.1.102  #需要根据环境调整
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  name: discovery-eureka-peer2
  labels:
    name: discovery-eureka-peer2-service
spec:
  ports:
    - name: "8762"
      port: 8762
      targetPort: 8762
  selector:
    name: discovery-eureka-peer2
  type: LoadBalancer
  externalIPs:
    - 192.168.1.103  #需要根据环境调整
status:
  loadBalancer: {}