apiVersion: v1
kind: Service
metadata:
  name: eureka-hl  #服务名称
spec:
  clusterIP: None  #无头服务
  ports:
    - name: "8761"
      port: 8761
      targetPort: 8761
  selector:
    workload.user.cattle.io/workloadselector: apps.statefulset-discovery-eureka
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-np
spec:
  #clusterIP:  192.168.1.102
  externalTrafficPolicy: Cluster
  ports:
    - name: "8761"
      nodePort: 30001
      port: 8761
      protocol: TCP
      targetPort: 8761
  selector:
    workload.user.cattle.io/workloadselector: apps.statefulset-discovery-eureka
  sessionAffinity: None
  type: NodePort