apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-gateway
  labels:
    name: orders-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      name: orders-gateway
  template:
    metadata:
      labels:
        name: orders-gateway
    spec:
      containers:
      - name: orders-gateway
        image: repo.orders.com:5000/orders/orders-gateway
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: peer1,prod
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://discovery-eureka-0.eureka-hl:8761/discovery/eureka/,http://discovery-eureka-1.eureka-hl:8761/discovery/eureka/
        ports:
        - containerPort: 8763