apiVersion: v1
kind: Service
metadata:
  name: orders-geteway
  labels:
    name: orders-geteway-service
spec:
  ports:
  - name: "8763"
    port: 8763
    targetPort: 8763
  selector:
    name: orders-geteway
  type: LoadBalancer
  externalIPs:
  - 192.168.1.102  #需要根据环境调整
  - 192.168.1.103  #需要根据环境调整
status:
  loadBalancer: {}
