apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      nodePort: 30014
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.12.2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/
      volumes:
        - name: config-volume
          configMap:
            name: nginx-cors-test
            items:
              - key: nginx.conf
                path: nginx.conf
