apiVersion: v1
kind: ReplicationController
metadata:
  name: orders_store_intra
  labels:
    name: orders_store_intra
spec:
  replicas: 2
  selector:
    name: orders_store_intra
  template:
    metadata:
      labels:
        name: orders_store_intra
    spec:
      containers:
      - name: product
        image: repo.orders.com:5000/orders/orders_store_intra
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            value: http://${DISCOVERY_EUREKA_PEER1_SERVICE_HOST}:${DISCOVERY_EUREKA_PEER1_SERVICE_PORT}/discovery/eureka/,http://${DISCOVERY_EUREKA_PEER2_SERVICE_HOST}:${DISCOVERY_EUREKA_PEER2_SERVICE_PORT}/discovery/eureka/
        ports:
        - containerPort: 8082