apiVersion: v1
kind: ReplicationController
metadata:
  name: orders-store-intra
  labels:
    name: orders-store-intra
spec:
  replicas: 2
  selector:
    name: orders-store-intra
  template:
    metadata:
      labels:
        name: orders-store-intra
    spec:
      containers:
      - name: orders-store-intra
        image: repo.orders.com:5000/orders/orders_store_intra
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            value: http://${DISCOVERY_EUREKA_PEER1_SERVICE_HOST}:${DISCOVERY_EUREKA_PEER1_SERVICE_PORT}/discovery/eureka/,http://${DISCOVERY_EUREKA_PEER2_SERVICE_HOST}:${DISCOVERY_EUREKA_PEER2_SERVICE_PORT}/discovery/eureka/
        ports:
        - containerPort: 8082
        volumeMounts:
          - name: logs
            mountPath: /logs
      - name: filebeat
        image: elastic/filebeat:7.10.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: logs
            mountPath: /logs
          - name: config
            mountPath: /usr/share/filebeat/filebeat.yml
            readOnly: true
            subPath: filebeat.yml

      volumes:
        - name: logs
          emptyDir: { }
        - name: config
          configMap:
            defaultMode: 420
            name: filebeat-conf