apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    name: product
spec:
  replicas: 2
  selector:
    matchLabels:
      name: product
  template:
    metadata:
      labels:
        name: product
    spec:
      dnsConfig:
        nameservers:
          - 192.168.1.6
          - 114.114.114.114
          - 8.8.8.8
        searches:
          - demo.svc.cluster.local
          - svc.cluster.local
          - cluster.local
        options:
          - name: ndots
            value: "2"
          - name: edns0
      containers:
      - name: product
        image: repo.orders.com:5000/orders/product
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
          - name: SPRING_DATASOURCE_HOST
            value: 192.168.1.6
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            value: http://discovery-eureka-0.eureka-hl:8761/discovery/eureka/,http://discovery-eureka-1.eureka-hl:8761/discovery/eureka/
        ports:
        - containerPort: 8082
        volumeMounts:
          - name: logs
            mountPath: /logs
      - name: filebeat
        image: elastic/filebeat:7.10.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: logs
            mountPath: /logs
          - name: config
            mountPath: /usr/share/filebeat/filebeat.yml
            readOnly: true
            subPath: filebeat.yml

      volumes:
        - name: logs
          emptyDir: {}
        - name: config
          configMap:
            defaultMode: 420
            name: filebeat-conf

