apiVersion: v1
kind: Service
metadata:
  name: product
  labels:
    name: product
spec:
  ports:
  - port: 8082
    targetPort: 8080
  selector:
    name: product
  type: LoadBalancer
  externalIPs:
  - 192.168.162.101  #需要根据环境调整