apiVersion: v1
kind: Service
metadata:
  name: product
  labels:
    name: product-service
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
  selector:
    name: product
  type: LoadBalancer
  externalIPs:
    - 192.168.1.102  #需要根据环境调整
    - 192.168.1.103  #需要根据环境调整
status:
  loadBalancer: {}