apiVersion: v1
kind: ReplicationController
metadata:
  name: product
  labels:
    name: product
spec:
  replicas: 2
  selector:
    name: product
  template:
    metadata:
      labels:
        name: product
    spec:
      containers:
      - name: product
        image: repo.orders.com:5000/orders/product
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
          - name: SPRING_DATASOURCE_HOST
            value: ${ORDERS_DB_SERVICE_HOST}
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            value: http://${DISCOVERY_EUREKA_PEER1_SERVICE_HOST}:${DISCOVERY_EUREKA_PEER1_SERVICE_PORT}/discovery/eureka/,http://${DISCOVERY_EUREKA_PEER2_SERVICE_HOST}:${DISCOVERY_EUREKA_PEER2_SERVICE_PORT}/discovery/eureka/
        ports:
        - containerPort: 8082