spring:
  profiles:
    active: peer1,dev
  application:
    name: orders-gateway
  cloud:
    gateway:
      enabled: true
      routes:
        - id: store_intra
          uri: ${remote.serviceUri.product}
          #order: 0
          predicates:
            - Path=/store_intra/**
          filters:
            - Auth
        - id: product
          uri: ${remote.serviceUri.product-api}
          #order: 0
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1

    loadbalancer:
      enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000

---
# peer1
spring:
  profiles: peer1
server:
  port: 8763
---
# peer2
spring:
  profiles: peer2
server:
  port: 8764

---
# 测试和生产环境
spring:
  profiles: test,prod

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #bus-api

remote:
  serviceUri:
    product: lb://orders-store-intra

#eureka:
#  client:
#    enabled: true
#    serviceUrl:
#      defaultZone: http://peer1:8761/discovery/eureka/,http://peer2:8762/discovery/eureka/
#    healthcheck:
#      enabled: true
#  instance:
#    prefer-ip-address: true
#    lease-expiration-duration-in-seconds: 30
#    lease-renewal-interval-in-seconds: 10


---
# 开发环境
spring:
  profiles: dev
#bus-api
remote:
  serviceUri:
    product: http://localhost:8083/store_intra
    product-api: lb://api-product

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://peer1:8761/discovery/eureka/,http://peer2:8762/discovery/eureka/
    healthcheck:
      enabled: true