spring:
  profiles:
    active: peer1,dev
  application:
    name: orders-gateway
  cloud:
    gateway:
      enabled: true
      routes:
        - id: store_intra
          uri: ${remote.serviceUri.product}
          #order: 0
          predicates:
            - Path=/store_intra/**
          filters:
            - Auth
        - id: product
          uri: ${remote.serviceUri.product-api}
          #order: 0
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1
        - id: orders
          uri: ${remote.serviceUri.orders-api}
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1

    loadbalancer:
      enabled: true
    sentinel:
      # 启用网关限流
      enabled: true
      # 取消控制台懒加载
      eager: true
      # 控制台配置
      transport:
        dashboard: localhost:1111
        # 与控制台通信的端口，默认8719，若被占用会自动从8719开始依次+1扫描
        port: 8719
      # 限流规则从Nacos动态加载，不再使用硬编码的全局QPS配置
      gateway:
      # 启用Nacos数据源，实现限流规则持久化
      datasource:
        ds:
          nacos:
            server-addr: localhost:8848
            dataId: gateway-sentinel-rules
            groupId: DEFAULT_GROUP
            rule-type: gw-flow

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000

---
# peer1
spring:
  profiles: peer1
server:
  port: 8763

---
# peer2
spring:
  profiles: peer2
server:
  port: 8764

---
# 测试和生产环境
spring:
  profiles: test,prod
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #bus-api

remote:
  serviceUri:
    product: lb://orders-store-intra

#eureka:
#  client:
#    enabled: true
#    serviceUrl:
#      defaultZone: http://peer1:8761/discovery/eureka/,http://peer2:8762/discovery/eureka/
#    healthcheck:
#      enabled: true
#  instance:
#    prefer-ip-address: true
#    lease-expiration-duration-in-seconds: 30
#    lease-renewal-interval-in-seconds: 10


---
# 开发环境
spring:
  profiles: dev
  cloud:
    sentinel:
      transport:
        dashboard: localhost:1111
        datasource:
          ds:
            nacos:
              server-addr: localhost:8848
              dataId: gateway-sentinel-rules-dev
              groupId: DEFAULT_GROUP
              rule-type: gw-flow
      # Sentinel命令行测试工具配置
      test:
        # 是否启用测试
        enabled: true
        # 并发线程数
        concurrent-threads: 5
        # 每线程请求数
        requests-per-thread: 5
#bus-api
remote:
  serviceUri:
    product: http://localhost:8083/store_intra
    product-api: lb://api-product
    orders-api: lb://api-orders

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://peer1:8761/discovery/eureka/,http://peer2:8762/discovery/eureka/
    healthcheck:
      enabled: true