package com.xiaoke_1256.orders.bigdata.orders.mapper;

import com.xiaoke_1256.orders.bigdata.orders.model.OrderItem;
import java.util.List;

public interface OrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Thu Aug 29 12:07:44 CST 2024
     */
    int deleteByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Thu Aug 29 12:07:44 CST 2024
     */
    int insert(OrderItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Thu Aug 29 12:07:44 CST 2024
     */
    OrderItem selectByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Thu Aug 29 12:07:44 CST 2024
     */
    List<OrderItem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Thu Aug 29 12:07:44 CST 2024
     */
    int updateByPrimaryKey(OrderItem row);
}