package com.xiaoke_1256.orders.bigdata.orders.mapper;

import com.xiaoke_1256.orders.bigdata.orders.model.PayOrder;
import java.util.List;

public interface PayOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated Wed Aug 28 16:06:51 CST 2024
     */
    int deleteByPrimaryKey(Long payOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated Wed Aug 28 16:06:51 CST 2024
     */
    int insert(PayOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated Wed Aug 28 16:06:51 CST 2024
     */
    PayOrder selectByPrimaryKey(Long payOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated Wed Aug 28 16:06:51 CST 2024
     */
    List<PayOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated Wed Aug 28 16:06:51 CST 2024
     */
    int updateByPrimaryKey(PayOrder row);
}