spring:
  profiles:
    active: peer1,dev
  application:
    name: discovery-eureka
server:
  context-path: /discovery
---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
    instance-id: peer1-8761
    #作为Eureka Client，把实例的ip的信息注册到eureka server中。
    #prefer-ip-address: true
    #leaseRenewalIntervalInSeconds: 10
    #leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/discovery/eureka/
    fetch-registry: true
    register-with-eureka: true
  server:
    #enable-self-preservation: false
    #eviction-interval-timer-in-ms: 10000
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
    instance-id: peer2-8762
    #作为Eureka Client，把实例的ip的信息注册到eureka server中。
    #prefer-ip-address: true
    #leaseRenewalIntervalInSeconds: 10
    #leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/discovery/eureka/
    fetch-registry: true
    register-with-eureka: true
  server:
    #enable-self-preservation: false
    #eviction-interval-timer-in-ms: 10000
  
