spring:
  profiles:
    active: peer1,dev
  application:
    name: discovery-eureka
server:
  context-path: /discovery
  port: 8761
eureka:
  instance:
    #作为Eureka Client，把实例的ip的信息注册到eureka server中。
    prefer-ip-address: true
    #leaseRenewalIntervalInSeconds: 10
    #leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/discovery/eureka/
    fetch-registry: true
    register-with-eureka: true
  server:
    #enable-self-preservation: false
    #eviction-interval-timer-in-ms: 10000

  
