package com.xiaoke_1256.orders.bigdata.aimode.model;

public class BigDataModelWithBLOBs extends BigDataModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data_model.file_content
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    private byte[] fileContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data_model.file_content
     *
     * @return the value of big_data_model.file_content
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    public byte[] getFileContent() {
        return fileContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data_model.file_content
     *
     * @param fileContent the value for big_data_model.file_content
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    public void setFileContent(byte[] fileContent) {
        this.fileContent = fileContent;
    }
}