package com.xiaoke_1256.orders.bigdata.aimode.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BigDataCalExecInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table big_data_cal_exec_info
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table big_data_cal_exec_info
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table big_data_cal_exec_info
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cal_exec_info
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    public BigDataCalExecInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cal_exec_info
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cal_exec_info
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cal_exec_info
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cal_exec_info
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cal_exec_info
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cal_exec_info
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cal_exec_info
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cal_exec_info
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cal_exec_info
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cal_exec_info
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table big_data_cal_exec_info
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andExecIdIsNull() {
            addCriterion("exec_id is null");
            return (Criteria) this;
        }

        public Criteria andExecIdIsNotNull() {
            addCriterion("exec_id is not null");
            return (Criteria) this;
        }

        public Criteria andExecIdEqualTo(Long value) {
            addCriterion("exec_id =", value, "execId");
            return (Criteria) this;
        }

        public Criteria andExecIdNotEqualTo(Long value) {
            addCriterion("exec_id <>", value, "execId");
            return (Criteria) this;
        }

        public Criteria andExecIdGreaterThan(Long value) {
            addCriterion("exec_id >", value, "execId");
            return (Criteria) this;
        }

        public Criteria andExecIdGreaterThanOrEqualTo(Long value) {
            addCriterion("exec_id >=", value, "execId");
            return (Criteria) this;
        }

        public Criteria andExecIdLessThan(Long value) {
            addCriterion("exec_id <", value, "execId");
            return (Criteria) this;
        }

        public Criteria andExecIdLessThanOrEqualTo(Long value) {
            addCriterion("exec_id <=", value, "execId");
            return (Criteria) this;
        }

        public Criteria andExecIdIn(List<Long> values) {
            addCriterion("exec_id in", values, "execId");
            return (Criteria) this;
        }

        public Criteria andExecIdNotIn(List<Long> values) {
            addCriterion("exec_id not in", values, "execId");
            return (Criteria) this;
        }

        public Criteria andExecIdBetween(Long value1, Long value2) {
            addCriterion("exec_id between", value1, value2, "execId");
            return (Criteria) this;
        }

        public Criteria andExecIdNotBetween(Long value1, Long value2) {
            addCriterion("exec_id not between", value1, value2, "execId");
            return (Criteria) this;
        }

        public Criteria andModelIdIsNull() {
            addCriterion("model_id is null");
            return (Criteria) this;
        }

        public Criteria andModelIdIsNotNull() {
            addCriterion("model_id is not null");
            return (Criteria) this;
        }

        public Criteria andModelIdEqualTo(Long value) {
            addCriterion("model_id =", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdNotEqualTo(Long value) {
            addCriterion("model_id <>", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdGreaterThan(Long value) {
            addCriterion("model_id >", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdGreaterThanOrEqualTo(Long value) {
            addCriterion("model_id >=", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdLessThan(Long value) {
            addCriterion("model_id <", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdLessThanOrEqualTo(Long value) {
            addCriterion("model_id <=", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdIn(List<Long> values) {
            addCriterion("model_id in", values, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdNotIn(List<Long> values) {
            addCriterion("model_id not in", values, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdBetween(Long value1, Long value2) {
            addCriterion("model_id between", value1, value2, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdNotBetween(Long value1, Long value2) {
            addCriterion("model_id not between", value1, value2, "modelId");
            return (Criteria) this;
        }

        public Criteria andObjectTypeIsNull() {
            addCriterion("object_type is null");
            return (Criteria) this;
        }

        public Criteria andObjectTypeIsNotNull() {
            addCriterion("object_type is not null");
            return (Criteria) this;
        }

        public Criteria andObjectTypeEqualTo(String value) {
            addCriterion("object_type =", value, "objectType");
            return (Criteria) this;
        }

        public Criteria andObjectTypeNotEqualTo(String value) {
            addCriterion("object_type <>", value, "objectType");
            return (Criteria) this;
        }

        public Criteria andObjectTypeGreaterThan(String value) {
            addCriterion("object_type >", value, "objectType");
            return (Criteria) this;
        }

        public Criteria andObjectTypeGreaterThanOrEqualTo(String value) {
            addCriterion("object_type >=", value, "objectType");
            return (Criteria) this;
        }

        public Criteria andObjectTypeLessThan(String value) {
            addCriterion("object_type <", value, "objectType");
            return (Criteria) this;
        }

        public Criteria andObjectTypeLessThanOrEqualTo(String value) {
            addCriterion("object_type <=", value, "objectType");
            return (Criteria) this;
        }

        public Criteria andObjectTypeLike(String value) {
            addCriterion("object_type like", value, "objectType");
            return (Criteria) this;
        }

        public Criteria andObjectTypeNotLike(String value) {
            addCriterion("object_type not like", value, "objectType");
            return (Criteria) this;
        }

        public Criteria andObjectTypeIn(List<String> values) {
            addCriterion("object_type in", values, "objectType");
            return (Criteria) this;
        }

        public Criteria andObjectTypeNotIn(List<String> values) {
            addCriterion("object_type not in", values, "objectType");
            return (Criteria) this;
        }

        public Criteria andObjectTypeBetween(String value1, String value2) {
            addCriterion("object_type between", value1, value2, "objectType");
            return (Criteria) this;
        }

        public Criteria andObjectTypeNotBetween(String value1, String value2) {
            addCriterion("object_type not between", value1, value2, "objectType");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTypeIsNull() {
            addCriterion("algorithm_type is null");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTypeIsNotNull() {
            addCriterion("algorithm_type is not null");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTypeEqualTo(String value) {
            addCriterion("algorithm_type =", value, "algorithmType");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTypeNotEqualTo(String value) {
            addCriterion("algorithm_type <>", value, "algorithmType");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTypeGreaterThan(String value) {
            addCriterion("algorithm_type >", value, "algorithmType");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTypeGreaterThanOrEqualTo(String value) {
            addCriterion("algorithm_type >=", value, "algorithmType");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTypeLessThan(String value) {
            addCriterion("algorithm_type <", value, "algorithmType");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTypeLessThanOrEqualTo(String value) {
            addCriterion("algorithm_type <=", value, "algorithmType");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTypeLike(String value) {
            addCriterion("algorithm_type like", value, "algorithmType");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTypeNotLike(String value) {
            addCriterion("algorithm_type not like", value, "algorithmType");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTypeIn(List<String> values) {
            addCriterion("algorithm_type in", values, "algorithmType");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTypeNotIn(List<String> values) {
            addCriterion("algorithm_type not in", values, "algorithmType");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTypeBetween(String value1, String value2) {
            addCriterion("algorithm_type between", value1, value2, "algorithmType");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTypeNotBetween(String value1, String value2) {
            addCriterion("algorithm_type not between", value1, value2, "algorithmType");
            return (Criteria) this;
        }

        public Criteria andExecuteTimeIsNull() {
            addCriterion("execute_time is null");
            return (Criteria) this;
        }

        public Criteria andExecuteTimeIsNotNull() {
            addCriterion("execute_time is not null");
            return (Criteria) this;
        }

        public Criteria andExecuteTimeEqualTo(Date value) {
            addCriterion("execute_time =", value, "executeTime");
            return (Criteria) this;
        }

        public Criteria andExecuteTimeNotEqualTo(Date value) {
            addCriterion("execute_time <>", value, "executeTime");
            return (Criteria) this;
        }

        public Criteria andExecuteTimeGreaterThan(Date value) {
            addCriterion("execute_time >", value, "executeTime");
            return (Criteria) this;
        }

        public Criteria andExecuteTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("execute_time >=", value, "executeTime");
            return (Criteria) this;
        }

        public Criteria andExecuteTimeLessThan(Date value) {
            addCriterion("execute_time <", value, "executeTime");
            return (Criteria) this;
        }

        public Criteria andExecuteTimeLessThanOrEqualTo(Date value) {
            addCriterion("execute_time <=", value, "executeTime");
            return (Criteria) this;
        }

        public Criteria andExecuteTimeIn(List<Date> values) {
            addCriterion("execute_time in", values, "executeTime");
            return (Criteria) this;
        }

        public Criteria andExecuteTimeNotIn(List<Date> values) {
            addCriterion("execute_time not in", values, "executeTime");
            return (Criteria) this;
        }

        public Criteria andExecuteTimeBetween(Date value1, Date value2) {
            addCriterion("execute_time between", value1, value2, "executeTime");
            return (Criteria) this;
        }

        public Criteria andExecuteTimeNotBetween(Date value1, Date value2) {
            addCriterion("execute_time not between", value1, value2, "executeTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table big_data_cal_exec_info
     *
     * @mbggenerated do_not_delete_during_merge Sat Sep 07 13:12:33 CST 2024
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table big_data_cal_exec_info
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}