package com.xiaoke_1256.orders.bigdata.aimode.model;

import java.util.Date;

public class BigDataCluster {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data_cluster.cluster_id
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    private Long clusterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data_cluster.exec_id
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    private Long execId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data_cluster.label
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    private String label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data_cluster.label_name
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    private String labelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data_cluster.insert_time
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    private Date insertTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data_cluster.cluster_id
     *
     * @return the value of big_data_cluster.cluster_id
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    public Long getClusterId() {
        return clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data_cluster.cluster_id
     *
     * @param clusterId the value for big_data_cluster.cluster_id
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    public void setClusterId(Long clusterId) {
        this.clusterId = clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data_cluster.exec_id
     *
     * @return the value of big_data_cluster.exec_id
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    public Long getExecId() {
        return execId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data_cluster.exec_id
     *
     * @param execId the value for big_data_cluster.exec_id
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    public void setExecId(Long execId) {
        this.execId = execId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data_cluster.label
     *
     * @return the value of big_data_cluster.label
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data_cluster.label
     *
     * @param label the value for big_data_cluster.label
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    public void setLabel(String label) {
        this.label = label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data_cluster.label_name
     *
     * @return the value of big_data_cluster.label_name
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    public String getLabelName() {
        return labelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data_cluster.label_name
     *
     * @param labelName the value for big_data_cluster.label_name
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    public void setLabelName(String labelName) {
        this.labelName = labelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data_cluster.insert_time
     *
     * @return the value of big_data_cluster.insert_time
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data_cluster.insert_time
     *
     * @param insertTime the value for big_data_cluster.insert_time
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }
}