package com.xiaoke_1256.orders.bigdata.aimode.model;

import java.util.Date;

public class BigDataModel extends BigDataModelKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data_model.model_name
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    private String modelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data_model.model_desc
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    private String modelDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data_model.model_type
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    private String modelType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data_model.algorithm_type
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    private String algorithmType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data_model.train_param
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    private String trainParam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data_model.class_define
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    private String classDefine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data_model.create_time
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data_model.create_by
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    private String createBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data_model.model_name
     *
     * @return the value of big_data_model.model_name
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data_model.model_name
     *
     * @param modelName the value for big_data_model.model_name
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    public void setModelName(String modelName) {
        this.modelName = modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data_model.model_desc
     *
     * @return the value of big_data_model.model_desc
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    public String getModelDesc() {
        return modelDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data_model.model_desc
     *
     * @param modelDesc the value for big_data_model.model_desc
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    public void setModelDesc(String modelDesc) {
        this.modelDesc = modelDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data_model.model_type
     *
     * @return the value of big_data_model.model_type
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    public String getModelType() {
        return modelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data_model.model_type
     *
     * @param modelType the value for big_data_model.model_type
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    public void setModelType(String modelType) {
        this.modelType = modelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data_model.algorithm_type
     *
     * @return the value of big_data_model.algorithm_type
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    public String getAlgorithmType() {
        return algorithmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data_model.algorithm_type
     *
     * @param algorithmType the value for big_data_model.algorithm_type
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    public void setAlgorithmType(String algorithmType) {
        this.algorithmType = algorithmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data_model.train_param
     *
     * @return the value of big_data_model.train_param
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    public String getTrainParam() {
        return trainParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data_model.train_param
     *
     * @param trainParam the value for big_data_model.train_param
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    public void setTrainParam(String trainParam) {
        this.trainParam = trainParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data_model.class_define
     *
     * @return the value of big_data_model.class_define
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    public String getClassDefine() {
        return classDefine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data_model.class_define
     *
     * @param classDefine the value for big_data_model.class_define
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    public void setClassDefine(String classDefine) {
        this.classDefine = classDefine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data_model.create_time
     *
     * @return the value of big_data_model.create_time
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data_model.create_time
     *
     * @param createTime the value for big_data_model.create_time
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data_model.create_by
     *
     * @return the value of big_data_model.create_by
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data_model.create_by
     *
     * @param createBy the value for big_data_model.create_by
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }
}