package com.xiaoke_1256.orders.bigdata.aimode.model;

import java.util.Date;

public class BigDataCalExecInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data_cal_exec_info.exec_id
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    private Long execId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data_cal_exec_info.model_id
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    private Long modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data_cal_exec_info.object_type
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    private String objectType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data_cal_exec_info.algorithm_type
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    private String algorithmType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data_cal_exec_info.execute_time
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    private Date executeTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data_cal_exec_info.exec_id
     *
     * @return the value of big_data_cal_exec_info.exec_id
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    public Long getExecId() {
        return execId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data_cal_exec_info.exec_id
     *
     * @param execId the value for big_data_cal_exec_info.exec_id
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    public void setExecId(Long execId) {
        this.execId = execId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data_cal_exec_info.model_id
     *
     * @return the value of big_data_cal_exec_info.model_id
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    public Long getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data_cal_exec_info.model_id
     *
     * @param modelId the value for big_data_cal_exec_info.model_id
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    public void setModelId(Long modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data_cal_exec_info.object_type
     *
     * @return the value of big_data_cal_exec_info.object_type
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    public String getObjectType() {
        return objectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data_cal_exec_info.object_type
     *
     * @param objectType the value for big_data_cal_exec_info.object_type
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    public void setObjectType(String objectType) {
        this.objectType = objectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data_cal_exec_info.algorithm_type
     *
     * @return the value of big_data_cal_exec_info.algorithm_type
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    public String getAlgorithmType() {
        return algorithmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data_cal_exec_info.algorithm_type
     *
     * @param algorithmType the value for big_data_cal_exec_info.algorithm_type
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    public void setAlgorithmType(String algorithmType) {
        this.algorithmType = algorithmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data_cal_exec_info.execute_time
     *
     * @return the value of big_data_cal_exec_info.execute_time
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    public Date getExecuteTime() {
        return executeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data_cal_exec_info.execute_time
     *
     * @param executeTime the value for big_data_cal_exec_info.execute_time
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    public void setExecuteTime(Date executeTime) {
        this.executeTime = executeTime;
    }
}