package com.xiaoke_1256.orders.bigdata.aimode.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BigDataModelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table big_data_model
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table big_data_model
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table big_data_model
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_model
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    public BigDataModelExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_model
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_model
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_model
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_model
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_model
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_model
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_model
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_model
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_model
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_model
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table big_data_model
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andModelIdIsNull() {
            addCriterion("model_id is null");
            return (Criteria) this;
        }

        public Criteria andModelIdIsNotNull() {
            addCriterion("model_id is not null");
            return (Criteria) this;
        }

        public Criteria andModelIdEqualTo(Long value) {
            addCriterion("model_id =", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdNotEqualTo(Long value) {
            addCriterion("model_id <>", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdGreaterThan(Long value) {
            addCriterion("model_id >", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdGreaterThanOrEqualTo(Long value) {
            addCriterion("model_id >=", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdLessThan(Long value) {
            addCriterion("model_id <", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdLessThanOrEqualTo(Long value) {
            addCriterion("model_id <=", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdIn(List<Long> values) {
            addCriterion("model_id in", values, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdNotIn(List<Long> values) {
            addCriterion("model_id not in", values, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdBetween(Long value1, Long value2) {
            addCriterion("model_id between", value1, value2, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdNotBetween(Long value1, Long value2) {
            addCriterion("model_id not between", value1, value2, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelNameIsNull() {
            addCriterion("model_name is null");
            return (Criteria) this;
        }

        public Criteria andModelNameIsNotNull() {
            addCriterion("model_name is not null");
            return (Criteria) this;
        }

        public Criteria andModelNameEqualTo(String value) {
            addCriterion("model_name =", value, "modelName");
            return (Criteria) this;
        }

        public Criteria andModelNameNotEqualTo(String value) {
            addCriterion("model_name <>", value, "modelName");
            return (Criteria) this;
        }

        public Criteria andModelNameGreaterThan(String value) {
            addCriterion("model_name >", value, "modelName");
            return (Criteria) this;
        }

        public Criteria andModelNameGreaterThanOrEqualTo(String value) {
            addCriterion("model_name >=", value, "modelName");
            return (Criteria) this;
        }

        public Criteria andModelNameLessThan(String value) {
            addCriterion("model_name <", value, "modelName");
            return (Criteria) this;
        }

        public Criteria andModelNameLessThanOrEqualTo(String value) {
            addCriterion("model_name <=", value, "modelName");
            return (Criteria) this;
        }

        public Criteria andModelNameLike(String value) {
            addCriterion("model_name like", value, "modelName");
            return (Criteria) this;
        }

        public Criteria andModelNameNotLike(String value) {
            addCriterion("model_name not like", value, "modelName");
            return (Criteria) this;
        }

        public Criteria andModelNameIn(List<String> values) {
            addCriterion("model_name in", values, "modelName");
            return (Criteria) this;
        }

        public Criteria andModelNameNotIn(List<String> values) {
            addCriterion("model_name not in", values, "modelName");
            return (Criteria) this;
        }

        public Criteria andModelNameBetween(String value1, String value2) {
            addCriterion("model_name between", value1, value2, "modelName");
            return (Criteria) this;
        }

        public Criteria andModelNameNotBetween(String value1, String value2) {
            addCriterion("model_name not between", value1, value2, "modelName");
            return (Criteria) this;
        }

        public Criteria andModelDescIsNull() {
            addCriterion("model_desc is null");
            return (Criteria) this;
        }

        public Criteria andModelDescIsNotNull() {
            addCriterion("model_desc is not null");
            return (Criteria) this;
        }

        public Criteria andModelDescEqualTo(String value) {
            addCriterion("model_desc =", value, "modelDesc");
            return (Criteria) this;
        }

        public Criteria andModelDescNotEqualTo(String value) {
            addCriterion("model_desc <>", value, "modelDesc");
            return (Criteria) this;
        }

        public Criteria andModelDescGreaterThan(String value) {
            addCriterion("model_desc >", value, "modelDesc");
            return (Criteria) this;
        }

        public Criteria andModelDescGreaterThanOrEqualTo(String value) {
            addCriterion("model_desc >=", value, "modelDesc");
            return (Criteria) this;
        }

        public Criteria andModelDescLessThan(String value) {
            addCriterion("model_desc <", value, "modelDesc");
            return (Criteria) this;
        }

        public Criteria andModelDescLessThanOrEqualTo(String value) {
            addCriterion("model_desc <=", value, "modelDesc");
            return (Criteria) this;
        }

        public Criteria andModelDescLike(String value) {
            addCriterion("model_desc like", value, "modelDesc");
            return (Criteria) this;
        }

        public Criteria andModelDescNotLike(String value) {
            addCriterion("model_desc not like", value, "modelDesc");
            return (Criteria) this;
        }

        public Criteria andModelDescIn(List<String> values) {
            addCriterion("model_desc in", values, "modelDesc");
            return (Criteria) this;
        }

        public Criteria andModelDescNotIn(List<String> values) {
            addCriterion("model_desc not in", values, "modelDesc");
            return (Criteria) this;
        }

        public Criteria andModelDescBetween(String value1, String value2) {
            addCriterion("model_desc between", value1, value2, "modelDesc");
            return (Criteria) this;
        }

        public Criteria andModelDescNotBetween(String value1, String value2) {
            addCriterion("model_desc not between", value1, value2, "modelDesc");
            return (Criteria) this;
        }

        public Criteria andModelTypeIsNull() {
            addCriterion("model_type is null");
            return (Criteria) this;
        }

        public Criteria andModelTypeIsNotNull() {
            addCriterion("model_type is not null");
            return (Criteria) this;
        }

        public Criteria andModelTypeEqualTo(String value) {
            addCriterion("model_type =", value, "modelType");
            return (Criteria) this;
        }

        public Criteria andModelTypeNotEqualTo(String value) {
            addCriterion("model_type <>", value, "modelType");
            return (Criteria) this;
        }

        public Criteria andModelTypeGreaterThan(String value) {
            addCriterion("model_type >", value, "modelType");
            return (Criteria) this;
        }

        public Criteria andModelTypeGreaterThanOrEqualTo(String value) {
            addCriterion("model_type >=", value, "modelType");
            return (Criteria) this;
        }

        public Criteria andModelTypeLessThan(String value) {
            addCriterion("model_type <", value, "modelType");
            return (Criteria) this;
        }

        public Criteria andModelTypeLessThanOrEqualTo(String value) {
            addCriterion("model_type <=", value, "modelType");
            return (Criteria) this;
        }

        public Criteria andModelTypeLike(String value) {
            addCriterion("model_type like", value, "modelType");
            return (Criteria) this;
        }

        public Criteria andModelTypeNotLike(String value) {
            addCriterion("model_type not like", value, "modelType");
            return (Criteria) this;
        }

        public Criteria andModelTypeIn(List<String> values) {
            addCriterion("model_type in", values, "modelType");
            return (Criteria) this;
        }

        public Criteria andModelTypeNotIn(List<String> values) {
            addCriterion("model_type not in", values, "modelType");
            return (Criteria) this;
        }

        public Criteria andModelTypeBetween(String value1, String value2) {
            addCriterion("model_type between", value1, value2, "modelType");
            return (Criteria) this;
        }

        public Criteria andModelTypeNotBetween(String value1, String value2) {
            addCriterion("model_type not between", value1, value2, "modelType");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTypeIsNull() {
            addCriterion("algorithm_type is null");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTypeIsNotNull() {
            addCriterion("algorithm_type is not null");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTypeEqualTo(String value) {
            addCriterion("algorithm_type =", value, "algorithmType");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTypeNotEqualTo(String value) {
            addCriterion("algorithm_type <>", value, "algorithmType");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTypeGreaterThan(String value) {
            addCriterion("algorithm_type >", value, "algorithmType");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTypeGreaterThanOrEqualTo(String value) {
            addCriterion("algorithm_type >=", value, "algorithmType");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTypeLessThan(String value) {
            addCriterion("algorithm_type <", value, "algorithmType");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTypeLessThanOrEqualTo(String value) {
            addCriterion("algorithm_type <=", value, "algorithmType");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTypeLike(String value) {
            addCriterion("algorithm_type like", value, "algorithmType");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTypeNotLike(String value) {
            addCriterion("algorithm_type not like", value, "algorithmType");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTypeIn(List<String> values) {
            addCriterion("algorithm_type in", values, "algorithmType");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTypeNotIn(List<String> values) {
            addCriterion("algorithm_type not in", values, "algorithmType");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTypeBetween(String value1, String value2) {
            addCriterion("algorithm_type between", value1, value2, "algorithmType");
            return (Criteria) this;
        }

        public Criteria andAlgorithmTypeNotBetween(String value1, String value2) {
            addCriterion("algorithm_type not between", value1, value2, "algorithmType");
            return (Criteria) this;
        }

        public Criteria andTrainParamIsNull() {
            addCriterion("train_param is null");
            return (Criteria) this;
        }

        public Criteria andTrainParamIsNotNull() {
            addCriterion("train_param is not null");
            return (Criteria) this;
        }

        public Criteria andTrainParamEqualTo(String value) {
            addCriterion("train_param =", value, "trainParam");
            return (Criteria) this;
        }

        public Criteria andTrainParamNotEqualTo(String value) {
            addCriterion("train_param <>", value, "trainParam");
            return (Criteria) this;
        }

        public Criteria andTrainParamGreaterThan(String value) {
            addCriterion("train_param >", value, "trainParam");
            return (Criteria) this;
        }

        public Criteria andTrainParamGreaterThanOrEqualTo(String value) {
            addCriterion("train_param >=", value, "trainParam");
            return (Criteria) this;
        }

        public Criteria andTrainParamLessThan(String value) {
            addCriterion("train_param <", value, "trainParam");
            return (Criteria) this;
        }

        public Criteria andTrainParamLessThanOrEqualTo(String value) {
            addCriterion("train_param <=", value, "trainParam");
            return (Criteria) this;
        }

        public Criteria andTrainParamLike(String value) {
            addCriterion("train_param like", value, "trainParam");
            return (Criteria) this;
        }

        public Criteria andTrainParamNotLike(String value) {
            addCriterion("train_param not like", value, "trainParam");
            return (Criteria) this;
        }

        public Criteria andTrainParamIn(List<String> values) {
            addCriterion("train_param in", values, "trainParam");
            return (Criteria) this;
        }

        public Criteria andTrainParamNotIn(List<String> values) {
            addCriterion("train_param not in", values, "trainParam");
            return (Criteria) this;
        }

        public Criteria andTrainParamBetween(String value1, String value2) {
            addCriterion("train_param between", value1, value2, "trainParam");
            return (Criteria) this;
        }

        public Criteria andTrainParamNotBetween(String value1, String value2) {
            addCriterion("train_param not between", value1, value2, "trainParam");
            return (Criteria) this;
        }

        public Criteria andClassDefineIsNull() {
            addCriterion("class_define is null");
            return (Criteria) this;
        }

        public Criteria andClassDefineIsNotNull() {
            addCriterion("class_define is not null");
            return (Criteria) this;
        }

        public Criteria andClassDefineEqualTo(String value) {
            addCriterion("class_define =", value, "classDefine");
            return (Criteria) this;
        }

        public Criteria andClassDefineNotEqualTo(String value) {
            addCriterion("class_define <>", value, "classDefine");
            return (Criteria) this;
        }

        public Criteria andClassDefineGreaterThan(String value) {
            addCriterion("class_define >", value, "classDefine");
            return (Criteria) this;
        }

        public Criteria andClassDefineGreaterThanOrEqualTo(String value) {
            addCriterion("class_define >=", value, "classDefine");
            return (Criteria) this;
        }

        public Criteria andClassDefineLessThan(String value) {
            addCriterion("class_define <", value, "classDefine");
            return (Criteria) this;
        }

        public Criteria andClassDefineLessThanOrEqualTo(String value) {
            addCriterion("class_define <=", value, "classDefine");
            return (Criteria) this;
        }

        public Criteria andClassDefineLike(String value) {
            addCriterion("class_define like", value, "classDefine");
            return (Criteria) this;
        }

        public Criteria andClassDefineNotLike(String value) {
            addCriterion("class_define not like", value, "classDefine");
            return (Criteria) this;
        }

        public Criteria andClassDefineIn(List<String> values) {
            addCriterion("class_define in", values, "classDefine");
            return (Criteria) this;
        }

        public Criteria andClassDefineNotIn(List<String> values) {
            addCriterion("class_define not in", values, "classDefine");
            return (Criteria) this;
        }

        public Criteria andClassDefineBetween(String value1, String value2) {
            addCriterion("class_define between", value1, value2, "classDefine");
            return (Criteria) this;
        }

        public Criteria andClassDefineNotBetween(String value1, String value2) {
            addCriterion("class_define not between", value1, value2, "classDefine");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("create_by is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("create_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(String value) {
            addCriterion("create_by =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(String value) {
            addCriterion("create_by <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(String value) {
            addCriterion("create_by >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("create_by >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(String value) {
            addCriterion("create_by <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(String value) {
            addCriterion("create_by <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLike(String value) {
            addCriterion("create_by like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotLike(String value) {
            addCriterion("create_by not like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<String> values) {
            addCriterion("create_by in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<String> values) {
            addCriterion("create_by not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(String value1, String value2) {
            addCriterion("create_by between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(String value1, String value2) {
            addCriterion("create_by not between", value1, value2, "createBy");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table big_data_model
     *
     * @mbg.generated do_not_delete_during_merge Tue Sep 03 17:06:04 CST 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table big_data_model
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}