package com.xiaoke_1256.orders.bigdata.aimode.model;

public class BigDataModelKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data_model.model_id
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    private Long modelId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data_model.model_id
     *
     * @return the value of big_data_model.model_id
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    public Long getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data_model.model_id
     *
     * @param modelId the value for big_data_model.model_id
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    public void setModelId(Long modelId) {
        this.modelId = modelId;
    }
}