package com.xiaoke_1256.orders.bigdata.aimode.model;

import java.util.Date;

public class BigDataClusterObjectMap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data_cluster_object_map.map_id
     *
     * @mbggenerated Sun Sep 08 14:35:38 CST 2024
     */
    private Long mapId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data_cluster_object_map.exec_id
     *
     * @mbggenerated Sun Sep 08 14:35:38 CST 2024
     */
    private Long execId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data_cluster_object_map.label
     *
     * @mbggenerated Sun Sep 08 14:35:38 CST 2024
     */
    private String label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data_cluster_object_map.object_type
     *
     * @mbggenerated Sun Sep 08 14:35:38 CST 2024
     */
    private String objectType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data_cluster_object_map.object_id
     *
     * @mbggenerated Sun Sep 08 14:35:38 CST 2024
     */
    private String objectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data_cluster_object_map.insert_time
     *
     * @mbggenerated Sun Sep 08 14:35:38 CST 2024
     */
    private Date insertTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data_cluster_object_map.map_id
     *
     * @return the value of big_data_cluster_object_map.map_id
     *
     * @mbggenerated Sun Sep 08 14:35:38 CST 2024
     */
    public Long getMapId() {
        return mapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data_cluster_object_map.map_id
     *
     * @param mapId the value for big_data_cluster_object_map.map_id
     *
     * @mbggenerated Sun Sep 08 14:35:38 CST 2024
     */
    public void setMapId(Long mapId) {
        this.mapId = mapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data_cluster_object_map.exec_id
     *
     * @return the value of big_data_cluster_object_map.exec_id
     *
     * @mbggenerated Sun Sep 08 14:35:38 CST 2024
     */
    public Long getExecId() {
        return execId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data_cluster_object_map.exec_id
     *
     * @param execId the value for big_data_cluster_object_map.exec_id
     *
     * @mbggenerated Sun Sep 08 14:35:38 CST 2024
     */
    public void setExecId(Long execId) {
        this.execId = execId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data_cluster_object_map.label
     *
     * @return the value of big_data_cluster_object_map.label
     *
     * @mbggenerated Sun Sep 08 14:35:38 CST 2024
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data_cluster_object_map.label
     *
     * @param label the value for big_data_cluster_object_map.label
     *
     * @mbggenerated Sun Sep 08 14:35:38 CST 2024
     */
    public void setLabel(String label) {
        this.label = label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data_cluster_object_map.object_type
     *
     * @return the value of big_data_cluster_object_map.object_type
     *
     * @mbggenerated Sun Sep 08 14:35:38 CST 2024
     */
    public String getObjectType() {
        return objectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data_cluster_object_map.object_type
     *
     * @param objectType the value for big_data_cluster_object_map.object_type
     *
     * @mbggenerated Sun Sep 08 14:35:38 CST 2024
     */
    public void setObjectType(String objectType) {
        this.objectType = objectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data_cluster_object_map.object_id
     *
     * @return the value of big_data_cluster_object_map.object_id
     *
     * @mbggenerated Sun Sep 08 14:35:38 CST 2024
     */
    public String getObjectId() {
        return objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data_cluster_object_map.object_id
     *
     * @param objectId the value for big_data_cluster_object_map.object_id
     *
     * @mbggenerated Sun Sep 08 14:35:38 CST 2024
     */
    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data_cluster_object_map.insert_time
     *
     * @return the value of big_data_cluster_object_map.insert_time
     *
     * @mbggenerated Sun Sep 08 14:35:38 CST 2024
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data_cluster_object_map.insert_time
     *
     * @param insertTime the value for big_data_cluster_object_map.insert_time
     *
     * @mbggenerated Sun Sep 08 14:35:38 CST 2024
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }
}