package com.xiaoke_1256.orders.bigdata.aimode.model;

import java.util.Date;

public class BigDataClusterDefined {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data_cluster_defined.cluster_id
     *
     * @mbggenerated Sun Sep 08 13:52:06 CST 2024
     */
    private Long clusterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data_cluster_defined.model_id
     *
     * @mbggenerated Sun Sep 08 13:52:06 CST 2024
     */
    private Long modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data_cluster_defined.label
     *
     * @mbggenerated Sun Sep 08 13:52:06 CST 2024
     */
    private String label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data_cluster_defined.label_name
     *
     * @mbggenerated Sun Sep 08 13:52:06 CST 2024
     */
    private String labelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data_cluster_defined.insert_time
     *
     * @mbggenerated Sun Sep 08 13:52:06 CST 2024
     */
    private Date insertTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data_cluster_defined.cluster_id
     *
     * @return the value of big_data_cluster_defined.cluster_id
     *
     * @mbggenerated Sun Sep 08 13:52:06 CST 2024
     */
    public Long getClusterId() {
        return clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data_cluster_defined.cluster_id
     *
     * @param clusterId the value for big_data_cluster_defined.cluster_id
     *
     * @mbggenerated Sun Sep 08 13:52:06 CST 2024
     */
    public void setClusterId(Long clusterId) {
        this.clusterId = clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data_cluster_defined.model_id
     *
     * @return the value of big_data_cluster_defined.model_id
     *
     * @mbggenerated Sun Sep 08 13:52:06 CST 2024
     */
    public Long getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data_cluster_defined.model_id
     *
     * @param modelId the value for big_data_cluster_defined.model_id
     *
     * @mbggenerated Sun Sep 08 13:52:06 CST 2024
     */
    public void setModelId(Long modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data_cluster_defined.label
     *
     * @return the value of big_data_cluster_defined.label
     *
     * @mbggenerated Sun Sep 08 13:52:06 CST 2024
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data_cluster_defined.label
     *
     * @param label the value for big_data_cluster_defined.label
     *
     * @mbggenerated Sun Sep 08 13:52:06 CST 2024
     */
    public void setLabel(String label) {
        this.label = label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data_cluster_defined.label_name
     *
     * @return the value of big_data_cluster_defined.label_name
     *
     * @mbggenerated Sun Sep 08 13:52:06 CST 2024
     */
    public String getLabelName() {
        return labelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data_cluster_defined.label_name
     *
     * @param labelName the value for big_data_cluster_defined.label_name
     *
     * @mbggenerated Sun Sep 08 13:52:06 CST 2024
     */
    public void setLabelName(String labelName) {
        this.labelName = labelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data_cluster_defined.insert_time
     *
     * @return the value of big_data_cluster_defined.insert_time
     *
     * @mbggenerated Sun Sep 08 13:52:06 CST 2024
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data_cluster_defined.insert_time
     *
     * @param insertTime the value for big_data_cluster_defined.insert_time
     *
     * @mbggenerated Sun Sep 08 13:52:06 CST 2024
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }
}