package com.xiaoke_1256.orders.bigdata.aimode.mapper;

import com.xiaoke_1256.orders.bigdata.aimode.model.BigDataCluster;
import com.xiaoke_1256.orders.bigdata.aimode.model.BigDataClusterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BigDataClusterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cluster
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    int countByExample(BigDataClusterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cluster
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    int deleteByExample(BigDataClusterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cluster
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    int deleteByPrimaryKey(Long clusterId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cluster
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    int insert(BigDataCluster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cluster
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    int insertSelective(BigDataCluster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cluster
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    List<BigDataCluster> selectByExampleWithRowbounds(BigDataClusterExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cluster
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    List<BigDataCluster> selectByExample(BigDataClusterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cluster
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    BigDataCluster selectByPrimaryKey(Long clusterId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cluster
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    int updateByExampleSelective(@Param("record") BigDataCluster record, @Param("example") BigDataClusterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cluster
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    int updateByExample(@Param("record") BigDataCluster record, @Param("example") BigDataClusterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cluster
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    int updateByPrimaryKeySelective(BigDataCluster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cluster
     *
     * @mbggenerated Sat Sep 07 13:12:33 CST 2024
     */
    int updateByPrimaryKey(BigDataCluster record);
}