package com.xiaoke_1256.orders.bigdata.aimode.mapper;

import com.xiaoke_1256.orders.bigdata.aimode.model.BigDataClusterObjectMap;
import com.xiaoke_1256.orders.bigdata.aimode.model.BigDataClusterObjectMapExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BigDataClusterObjectMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cluster_object_map
     *
     * @mbggenerated Sun Sep 08 14:35:38 CST 2024
     */
    int countByExample(BigDataClusterObjectMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cluster_object_map
     *
     * @mbggenerated Sun Sep 08 14:35:38 CST 2024
     */
    int deleteByExample(BigDataClusterObjectMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cluster_object_map
     *
     * @mbggenerated Sun Sep 08 14:35:38 CST 2024
     */
    int deleteByPrimaryKey(Long mapId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cluster_object_map
     *
     * @mbggenerated Sun Sep 08 14:35:38 CST 2024
     */
    int insert(BigDataClusterObjectMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cluster_object_map
     *
     * @mbggenerated Sun Sep 08 14:35:38 CST 2024
     */
    int insertSelective(BigDataClusterObjectMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cluster_object_map
     *
     * @mbggenerated Sun Sep 08 14:35:38 CST 2024
     */
    List<BigDataClusterObjectMap> selectByExampleWithRowbounds(BigDataClusterObjectMapExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cluster_object_map
     *
     * @mbggenerated Sun Sep 08 14:35:38 CST 2024
     */
    List<BigDataClusterObjectMap> selectByExample(BigDataClusterObjectMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cluster_object_map
     *
     * @mbggenerated Sun Sep 08 14:35:38 CST 2024
     */
    BigDataClusterObjectMap selectByPrimaryKey(Long mapId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cluster_object_map
     *
     * @mbggenerated Sun Sep 08 14:35:38 CST 2024
     */
    int updateByExampleSelective(@Param("record") BigDataClusterObjectMap record, @Param("example") BigDataClusterObjectMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cluster_object_map
     *
     * @mbggenerated Sun Sep 08 14:35:38 CST 2024
     */
    int updateByExample(@Param("record") BigDataClusterObjectMap record, @Param("example") BigDataClusterObjectMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cluster_object_map
     *
     * @mbggenerated Sun Sep 08 14:35:38 CST 2024
     */
    int updateByPrimaryKeySelective(BigDataClusterObjectMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_cluster_object_map
     *
     * @mbggenerated Sun Sep 08 14:35:38 CST 2024
     */
    int updateByPrimaryKey(BigDataClusterObjectMap record);


    BigDataClusterObjectMap selectByModelIdAndObjectId(@Param("objectType")String objectType, @Param("objectId") String objectId, @Param("modelId")Long modelId );
}