package com.xiaoke_1256.orders.bigdata.aimode.mapper;

import com.xiaoke_1256.orders.bigdata.aimode.model.BigDataModel;
import com.xiaoke_1256.orders.bigdata.aimode.model.BigDataModelExample;
import com.xiaoke_1256.orders.bigdata.aimode.model.BigDataModelKey;
import com.xiaoke_1256.orders.bigdata.aimode.model.BigDataModelWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BigDataModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_model
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    long countByExample(BigDataModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_model
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    int deleteByExample(BigDataModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_model
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    int deleteByPrimaryKey(BigDataModelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_model
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    int insert(BigDataModelWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_model
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    int insertSelective(BigDataModelWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_model
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    List<BigDataModelWithBLOBs> selectByExampleWithBLOBsWithRowbounds(BigDataModelExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_model
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    List<BigDataModelWithBLOBs> selectByExampleWithBLOBs(BigDataModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_model
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    List<BigDataModel> selectByExampleWithRowbounds(BigDataModelExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_model
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    List<BigDataModel> selectByExample(BigDataModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_model
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    BigDataModelWithBLOBs selectByPrimaryKey(BigDataModelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_model
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    int updateByExampleSelective(@Param("row") BigDataModelWithBLOBs row, @Param("example") BigDataModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_model
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    int updateByExampleWithBLOBs(@Param("row") BigDataModelWithBLOBs row, @Param("example") BigDataModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_model
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    int updateByExample(@Param("row") BigDataModel row, @Param("example") BigDataModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_model
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    int updateByPrimaryKeySelective(BigDataModelWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_model
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    int updateByPrimaryKeyWithBLOBs(BigDataModelWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_model
     *
     * @mbg.generated Tue Sep 03 17:06:04 CST 2024
     */
    int updateByPrimaryKey(BigDataModel row);
}