package com.xiaoke_1256.orders.bigdata.orders.model;

import java.math.BigDecimal;

public class OrderItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.item_id
     *
     * @mbg.generated Thu Aug 29 12:07:44 CST 2024
     */
    private Long itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.pay_order_id
     *
     * @mbg.generated Thu Aug 29 12:07:44 CST 2024
     */
    private Long payOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.order_no
     *
     * @mbg.generated Thu Aug 29 12:07:44 CST 2024
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.product_code
     *
     * @mbg.generated Thu Aug 29 12:07:44 CST 2024
     */
    private String productCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.option_code
     *
     * @mbg.generated Thu Aug 29 12:07:44 CST 2024
     */
    private String optionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.product_price
     *
     * @mbg.generated Thu Aug 29 12:07:44 CST 2024
     */
    private BigDecimal productPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.product_num
     *
     * @mbg.generated Thu Aug 29 12:07:44 CST 2024
     */
    private Long productNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.item_id
     *
     * @return the value of order_item.item_id
     *
     * @mbg.generated Thu Aug 29 12:07:44 CST 2024
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.item_id
     *
     * @param itemId the value for order_item.item_id
     *
     * @mbg.generated Thu Aug 29 12:07:44 CST 2024
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.pay_order_id
     *
     * @return the value of order_item.pay_order_id
     *
     * @mbg.generated Thu Aug 29 12:07:44 CST 2024
     */
    public Long getPayOrderId() {
        return payOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.pay_order_id
     *
     * @param payOrderId the value for order_item.pay_order_id
     *
     * @mbg.generated Thu Aug 29 12:07:44 CST 2024
     */
    public void setPayOrderId(Long payOrderId) {
        this.payOrderId = payOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.order_no
     *
     * @return the value of order_item.order_no
     *
     * @mbg.generated Thu Aug 29 12:07:44 CST 2024
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.order_no
     *
     * @param orderNo the value for order_item.order_no
     *
     * @mbg.generated Thu Aug 29 12:07:44 CST 2024
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.product_code
     *
     * @return the value of order_item.product_code
     *
     * @mbg.generated Thu Aug 29 12:07:44 CST 2024
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.product_code
     *
     * @param productCode the value for order_item.product_code
     *
     * @mbg.generated Thu Aug 29 12:07:44 CST 2024
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.option_code
     *
     * @return the value of order_item.option_code
     *
     * @mbg.generated Thu Aug 29 12:07:44 CST 2024
     */
    public String getOptionCode() {
        return optionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.option_code
     *
     * @param optionCode the value for order_item.option_code
     *
     * @mbg.generated Thu Aug 29 12:07:44 CST 2024
     */
    public void setOptionCode(String optionCode) {
        this.optionCode = optionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.product_price
     *
     * @return the value of order_item.product_price
     *
     * @mbg.generated Thu Aug 29 12:07:44 CST 2024
     */
    public BigDecimal getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.product_price
     *
     * @param productPrice the value for order_item.product_price
     *
     * @mbg.generated Thu Aug 29 12:07:44 CST 2024
     */
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.product_num
     *
     * @return the value of order_item.product_num
     *
     * @mbg.generated Thu Aug 29 12:07:44 CST 2024
     */
    public Long getProductNum() {
        return productNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.product_num
     *
     * @param productNum the value for order_item.product_num
     *
     * @mbg.generated Thu Aug 29 12:07:44 CST 2024
     */
    public void setProductNum(Long productNum) {
        this.productNum = productNum;
    }
}