package com.xiaoke_1256.orders.bigdata.orders.model;

import java.math.BigDecimal;
import java.util.Date;

public class PayOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.pay_order_id
     *
     * @mbg.generated Wed Aug 28 16:06:51 CST 2024
     */
    private Long payOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.pay_order_no
     *
     * @mbg.generated Wed Aug 28 16:06:51 CST 2024
     */
    private String payOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.carriage_amt
     *
     * @mbg.generated Wed Aug 28 16:06:51 CST 2024
     */
    private BigDecimal carriageAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.payer_no
     *
     * @mbg.generated Wed Aug 28 16:06:51 CST 2024
     */
    private String payerNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.total_amt
     *
     * @mbg.generated Wed Aug 28 16:06:51 CST 2024
     */
    private BigDecimal totalAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.insert_time
     *
     * @mbg.generated Wed Aug 28 16:06:51 CST 2024
     */
    private Date insertTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.update_time
     *
     * @mbg.generated Wed Aug 28 16:06:51 CST 2024
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.STATUS
     *
     * @mbg.generated Wed Aug 28 16:06:51 CST 2024
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.pay_order_id
     *
     * @return the value of pay_order.pay_order_id
     *
     * @mbg.generated Wed Aug 28 16:06:51 CST 2024
     */
    public Long getPayOrderId() {
        return payOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.pay_order_id
     *
     * @param payOrderId the value for pay_order.pay_order_id
     *
     * @mbg.generated Wed Aug 28 16:06:51 CST 2024
     */
    public void setPayOrderId(Long payOrderId) {
        this.payOrderId = payOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.pay_order_no
     *
     * @return the value of pay_order.pay_order_no
     *
     * @mbg.generated Wed Aug 28 16:06:51 CST 2024
     */
    public String getPayOrderNo() {
        return payOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.pay_order_no
     *
     * @param payOrderNo the value for pay_order.pay_order_no
     *
     * @mbg.generated Wed Aug 28 16:06:51 CST 2024
     */
    public void setPayOrderNo(String payOrderNo) {
        this.payOrderNo = payOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.carriage_amt
     *
     * @return the value of pay_order.carriage_amt
     *
     * @mbg.generated Wed Aug 28 16:06:51 CST 2024
     */
    public BigDecimal getCarriageAmt() {
        return carriageAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.carriage_amt
     *
     * @param carriageAmt the value for pay_order.carriage_amt
     *
     * @mbg.generated Wed Aug 28 16:06:51 CST 2024
     */
    public void setCarriageAmt(BigDecimal carriageAmt) {
        this.carriageAmt = carriageAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.payer_no
     *
     * @return the value of pay_order.payer_no
     *
     * @mbg.generated Wed Aug 28 16:06:51 CST 2024
     */
    public String getPayerNo() {
        return payerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.payer_no
     *
     * @param payerNo the value for pay_order.payer_no
     *
     * @mbg.generated Wed Aug 28 16:06:51 CST 2024
     */
    public void setPayerNo(String payerNo) {
        this.payerNo = payerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.total_amt
     *
     * @return the value of pay_order.total_amt
     *
     * @mbg.generated Wed Aug 28 16:06:51 CST 2024
     */
    public BigDecimal getTotalAmt() {
        return totalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.total_amt
     *
     * @param totalAmt the value for pay_order.total_amt
     *
     * @mbg.generated Wed Aug 28 16:06:51 CST 2024
     */
    public void setTotalAmt(BigDecimal totalAmt) {
        this.totalAmt = totalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.insert_time
     *
     * @return the value of pay_order.insert_time
     *
     * @mbg.generated Wed Aug 28 16:06:51 CST 2024
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.insert_time
     *
     * @param insertTime the value for pay_order.insert_time
     *
     * @mbg.generated Wed Aug 28 16:06:51 CST 2024
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.update_time
     *
     * @return the value of pay_order.update_time
     *
     * @mbg.generated Wed Aug 28 16:06:51 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.update_time
     *
     * @param updateTime the value for pay_order.update_time
     *
     * @mbg.generated Wed Aug 28 16:06:51 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.STATUS
     *
     * @return the value of pay_order.STATUS
     *
     * @mbg.generated Wed Aug 28 16:06:51 CST 2024
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.STATUS
     *
     * @param status the value for pay_order.STATUS
     *
     * @mbg.generated Wed Aug 28 16:06:51 CST 2024
     */
    public void setStatus(String status) {
        this.status = status;
    }
}